### ISSUE TITLE
example file not working

### ISSUE THREAD

**Issue by MathieuRoule** [michael-petersen/JuliaOrbitElements#1]
- Comments """ ... """ at the begin of the file apparently must be followed by blank line 
> error: cannot document  "import OrbitalElements"

- unknown quantities : At least n1, n2, tabuGLquad

**Comment by michael-petersen** [comment]
Fixed with a couple of tweaks. Now both `examples/run_isochrone.jl` and `examples/run_inversions.jl` work out of the box. Closing this for now, but if anything doesn't work, can reopen!
